# Generated by Django 4.2.7 on 2023-12-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gdpr_consent',
            field=models.BooleanField(default=False),
        ),
    ]
