# Generated by Django 4.2.7 on 2023-12-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
