# Generated by Django 4.2.7 on 2023-12-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='H4XI6MEV', max_length=254, unique=True),
        ),
    ]
