# Generated by Django 4.2.7 on 2023-12-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='D73FQ8T4', max_length=254, unique=True),
        ),
    ]
