# Generated by Django 4.2.7 on 2023-12-12 13:36

from django.conf import settings
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=products.models.generate_sku, max_length=254, unique=True),
        ),
    ]
