# Generated by Django 4.2.7 on 2023-12-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_favorites_alter_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
