# Generated by Django 4.2.7 on 2024-01-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_options_product_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Discounted Price'),
        ),
    ]
